# Generated by Django 5.2.2 on 2026-04-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointmentrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('suggested', 'Alternative Suggested')], default='pending', max_length=20),
        ),
    ]
