# Generated by Django 5.1.15 on 2026-07-20 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointmentrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='awaiting_payment',
            field=models.BooleanField(default=False),
        ),
    ]
