# Generated by Django 5.1.15 on 2026-07-20 05:56

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0005_appointment_completed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(db_index=True, max_length=64)),
                ('status_id', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tran_id', models.BigIntegerField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(max_length=64, unique=True)),
                ('attempt', models.PositiveIntegerField(default=1)),
                ('receipt_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fee_rate', models.DecimalField(decimal_places=4, default=Decimal('0.20'), max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency_id', models.PositiveSmallIntegerField(default=2)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('expired', 'Expired'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partly_refunded', 'Partly Refunded')], default='pending', max_length=20)),
                ('shamcash_status_id', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('payment_url', models.TextField(blank=True)),
                ('tran_id', models.BigIntegerField(blank=True, null=True)),
                ('refund_idempotency_key', models.CharField(blank=True, max_length=100)),
                ('refund_tran_id', models.BigIntegerField(blank=True, null=True)),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('refund_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('appointment_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='appointments.appointmentrequest')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_received', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['doctor', 'status'], name='payments_pa_doctor__90e0cf_idx'), models.Index(fields=['status', 'paid_at'], name='payments_pa_status_bed4b8_idx')],
            },
        ),
        migrations.CreateModel(
            name='PayoutSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.PositiveIntegerField()),
                ('period_month', models.PositiveSmallIntegerField()),
                ('handled_count', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('currency_id', models.PositiveSmallIntegerField(default=2)),
                ('status', models.CharField(choices=[('due', 'Due'), ('paid', 'Paid')], default='due', max_length=10)),
                ('paid_reference', models.CharField(blank=True, max_length=120)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_settlements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_year', '-period_month'],
                'unique_together': {('doctor', 'period_year', 'period_month')},
            },
        ),
    ]
