# Generated by Django 5.1.15 on 2026-07-20 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_latitude_profile_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='receipt_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
