# Generated by Django 5.2.2 on 2026-04-12 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
        ('patients', '0002_alter_patient_options_patient_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='patients.patient'),
        ),
    ]
