# Generated by Django 5.2.2 on 2026-04-12 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_alter_medication_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('category', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='medication',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='medication',
            name='description',
        ),
        migrations.AddField(
            model_name='medication',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='frequency',
            field=models.CharField(choices=[('once_daily', 'Once Daily'), ('twice_daily', 'Twice Daily'), ('three_times_daily', 'Three Times Daily'), ('four_times_daily', 'Four Times Daily'), ('every_8_hours', 'Every 8 Hours'), ('every_12_hours', 'Every 12 Hours'), ('as_needed', 'As Needed'), ('weekly', 'Weekly')], default='once_daily', max_length=30),
        ),
        migrations.AddField(
            model_name='medication',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='route',
            field=models.CharField(choices=[('oral', 'Oral'), ('injection', 'Injection'), ('topical', 'Topical'), ('inhalation', 'Inhalation'), ('sublingual', 'Sublingual'), ('iv', 'Intravenous (IV)'), ('eye_drops', 'Eye Drops'), ('ear_drops', 'Ear Drops')], default='oral', max_length=20),
        ),
        migrations.AddField(
            model_name='medication',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
