# Generated by Django 5.2.2 on 2026-04-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_remove_report_created_by_remove_report_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='report',
            name='chief_complaint',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='examination',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='treatment_plan',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
